== Görüntü İşleme

== İçindekiler +
.İçindekiler +
. Versiyon Geçmişi +
. Bölüm 1 - Giriş +
. Bölüm 2 - Ağırlık toplama Yöntemi +
. Bölüm 3 - Python ile Ağırlık Toplama Yöntemi Uygulaması +
. Referanslar +

== Versiyon Geçmişi +

|===
|Tarih|Değişiklik|Kişi

|22.10.2016
| 

|Gönül TOKTAY
|25.10.2016

|
|Miraç Sıla GENÇ 
|===

== Giriş +

Görüntü işleme, genel olarak resimsel bilgilerin analizine yönelik bir yöntem olarak tanımlanabilir. Günlük yaşamda görüntü işlemenin en yaygın örneği gözlükler diyebiliriz. Numaralı gözlükler, gözlenen görüntüleri gözdeki bazı sapmalara göre değiştirip, görüntünün göz ile temasından önce görüntünün düzeltilmesi için görev görür. Görüntü işlemede amaç, orijinal şeklinde olmayan bir görüntüyü görsel olarak güçlendirmek ve istatistiksel olarak değerlendirmektir. Görüntü işleme algoritmaları olarak bilinen, görüntülerin iyileştirmesi veya değiştirilmesi için birçok görüntü işleme tekniği bulunmaktadır. +

Burada yapılacak olan çalışmanın ilk adımı olan görüntüyü griye çevirme işlemi anlatılacaktır. Görüntüyü griye çevirmek için kullanılacak olan görüntü işleme tekniği ‘Ağırlık Toplama Yönetimi’dir. Uygulamayı gerçekleştirebilmek için ağırlık toplama yönteminin ne olduğu, nasıl kullanıldığı  ve kullanım amaçlarından bahsedilecektir. +
